version: '3.7'

services:
  codeflex-db-dev:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.docker.dev
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./db-provision:/docker-entrypoint-initdb.d/
  app:
    build:
      context: ../
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env.docker.dev
    depends_on:
      - "codelfex-db-dev"
